version: '3.4'

services:
  matchingx:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    networks:
      - exchange

  postgres:
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - exchange

  adminer:
    restart: always
    ports:
      - 8080:8080
    networks:
      - exchange

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - exchange

  redis:
    container_name: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    networks:
      - exchange
  
  mongodb:
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - exchange

  orderentryx:
    container_name: orderentryx
    ports:
      - "5022:5022"
    networks:
      - exchange

volumes:
  mongo_data:
    driver: local

networks:
    exchange:
        driver: bridge