version: '3.4'

services:
  matchingx:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    networks:
      - exchange
  
  zookeeper:
    container_name: zookeeper
    restart: always
    ports:
      - "8080:8080"
      - "2181:2181"
  
  zoonavigator:
    container_name: zoonavigator 
    restart: unless-stopped
    ports:
      - "9000:9000"
  
  # postgres:
  #   container_name: postgres
  #   restart: always
  #   # set shared memory limit when using docker-compose
  #   shm_size: 128mb
  #   # or set shared memory limit when deploy via swarm stack
  #   #volumes:
  #   #  - type: tmpfs
  #   #    target: /dev/shm
  #   #    tmpfs:
  #   #      size: 134217728 # 128*2^20 bytes = 128Mb
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   networks:
  #     - exchange

  # adminer:
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - exchange

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - exchange

  redis:
    container_name: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    networks:
      - exchange
  
  mongodb:
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    # environment:
    #    MONGO_INITDB_ROOT_USERNAME: root
    #    MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      #- $PWD/.docker/mongo/replica.key:/data/replica.key.devel
      # - example/.docker/mongo/replica.key:/data/replica.key.devel
      # - example/.docker/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - exchange
  

  # orderentryx:
  #   container_name: orderentryx
  #   ports:
  #     - "5022:5022"
  #   networks:
  #     - exchange
  
  testenginex:
    container_name: testenginex
    ports:
      - "5023:5023"
    networks:
      - exchange

  orderenginex:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5024:5024"
    networks:
      - exchange

volumes:
  mongodb_data:
  mongodb_config:
    # driver: local

networks:
    exchange:
        driver: bridge
