version: '3.4'

services:
  matchingx:
    image: ${DOCKER_REGISTRY-}matching
    build:
      context: .
      dockerfile: MatchingX/MatchingX.ServerApp/Dockerfile
 
  orderentryx:
    image: ${DOCKER_REGISTRY-}orderentry
    build:
      context: .
      dockerfile: OrderEntryX/OrderEntryX.ServerApp/Dockerfile
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  mongodb:
    image: mongo
  
  postgres:
    image: postgres

  redis:
    image: redis
  
  adminer:
    image: adminer

  zookeeper:
    image: zookeeperSA
  
  zoonavigator:
    image: elkozmon/zoonavigator:latest