version: '3.4'

services:
  matchingx:
    image: ${DOCKER_REGISTRY-}matching
    build:
      context: .
      dockerfile: MatchingX/MatchingX.ServerApp/Dockerfile
 
  # orderentryx:
  #   image: ${DOCKER_REGISTRY-}orderentry
  #   build:
  #     context: .
  #     dockerfile: OrderEntryX/OrderEntryX.ServerApp/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  mongodb:
    image: mongo:7.0
  
  postgres:
    image: postgres

  redis:
    image: redis
  
  adminer:
    image: adminer

  zookeeper:
    image: zookeeper
  
  zoonavigator:
    image: elkozmon/zoonavigator:latest
  
  testenginex:
    image: ${DOCKER_REGISTRY-}testenginex
    build:
      context: .
      dockerfile: TestEngineX/TestEngineX/Dockerfile


  orderenginex:
    image: ${DOCKER_REGISTRY-}orderenginexapi
    build:
      context: .
      dockerfile: OrderEngineX/OrderX.API/Dockerfile

